// pch.h: This is a precompiled header file.
// Files listed below are compiled only once, improving build performance for future builds.
// This also affects IntelliSense performance, including code completion and many code browsing features.
// However, files listed here are ALL re-compiled if any one of them is updated between builds.
// Do not add files here that you will be updating frequently as this negates the performance advantage.

#ifndef PCH_H
#define PCH_H

#include <QAction>                   
#include <QApplication>              
#include <QBitmap>                   
#include <QBoxLayout>                
#include <QButtonGroup>              
#include <QByteArray>                
#include <QCalendarWidget>           
#include <QCheckBox>                 
#include <QClipboard>                
#include <QColor>                    
#include <QComboBox>                 
#include <QCompleter>                
#include <QCoreApplication>          
#include <QCryptographicHash>        
#include <QDateTime>                 
#include <QDebug>                    
#include <QDesktopServices>          
#include <QDesktopWidget>            
#include <QDialog>                   
#include <QDir>                      
#include <QDomDocument>              
#include <QDrag>                     
#include <QDragEnterEvent>           
#include <QDropEvent>                
#include <QEvent>                    
#include <QEventLoop>                
#include <QFile>                     
#include <QFileDialog>               
#include <QFileInfo>                 
#include <QFocusEvent>               
#include <QFont>                     
#include <QFontMetrics>              
#include <QGraphicsDropShadowEffect> 
#include <QGridLayout>               
#include <QGuiApplication>           
#include <QHBoxLayout>               
#include <QHash>                     
#include <QHelpEvent>                
#include <QHoverEvent>               
#include <QImage>                    
#include <QImageReader>              
#include <QJsonArray>                
#include <QJsonDocument>             
#include <QJsonObject>               
#include <QJsonParseError>           
#include <QJsonValue>                
#include <QKeyEvent>                 
#include <QLabel>                    
#include <QLayout>                   
#include <QLibrary>                  
#include <QLineEdit>                 
#include <QLinearGradient>           
#include <QList>                     
#include <QListView>                 
#include <QListWidget>               
#include <QListWidgetItem>           
#include <QLocalSocket>              
#include <QLocale>                   
#include <QMap>                      
#include <QMenu>                     
#include <QMessageBox>               
#include <QMetaObject>               
#include <QMimeData>                 
#include <QMouseEvent>               
#include <QMutex>                                  
#include <QNetworkAccessManager>     
#include <QNetworkProxyFactory>      
#include <QNetworkReply>             
#include <QNetworkRequest>           
#include <QObject>                   
#include <QPaintEvent>               
#include <QPainter>                  
#include <QPainterPath>              
#include <QPen>                      
#include <QPixmap>                   
#include <QPlainTextEdit>            
#include <QPoint>                    
#include <QPointer>                  
#include <QProgressBar>              
#include <QPushButton>               
#include <QQueue>                    
#include <QRadioButton>              
#include <QReadWriteLock>            
#include <QScreen>                   
#include <QScrollArea>               
#include <QScrollBar>                
#include <QScrollbar>                
#include <QSet>                      
#include <QSettings>                 
#include <QSharedMemory>             
#include <QSharedPointer>            
#include <QSignalMapper>             
#include <QSlider>                                     
#include <QSplitter>                 
#include <QSqlDatabase>              
#include <QSqlQuery>                 
#include <QStackedLayout>            
#include <QStackedWidget>            
#include <QStandardItemModel>        
#include <QString>                   
#include <QStringList>               
#include <QStringListModel>          
#include <QStyleOption>              
#include <QStylePainter>             
#include <QStyledItemDelegate>       
#include <QTabBar>                   
#include <QTabWidget>                
#include <QTextBlock>                
#include <QTextBrowser>              
#include <QTextEdit>                 
#include <QThread>                   
#include <QThreadPool>               
#include <QTimer>                    
#include <QTimerEvent>    
#include <QToolButton>               
#include <QToolTip>                  
#include <QTreeWidget>               
#include <QUuid>                     
#include <QVBoxLayout>               
#include <QVariant>                  
#include <QVector>                   
#include <QWebChannel>               
#include <QWebEnginePage>            
#include <QWebEngineProfile>         
#include <QWebEngineView>            
#include <QWidget>                   
#include <QWidgetAction>             
#include <QWindow>                   
#include <QXmlStreamReader>                       


#endif //PCH_H
