function (removeFilesFromList srcs out)
    #message("srcs: " ${srcs})
	#message("out: " ${out})
    #message("argn: " ${ARGN})
    file (GLOB_RECURSE to_remove ${ARGN})
	#message("to_remove: " ${to_remove})
    list (REMOVE_ITEM srcs ${to_remove})
	#message("after remove: " ${srcs})
    set (${out} ${srcs} PARENT_SCOPE)
endfunction()